### ISSUE TITLE
Pandas library and Errors 

### ISSUE THREAD

**Issue by OnlyHigh** [GenomicParisCentre/toulligQC#5]
Good afternoon, 
I'm setting this issue 'cause I have two running problems in two different computers: 
The first one is:  
```
Traceback (most recent call last):
  File "/usr/local/bin/toulligqc", line 11, in <module>
    load_entry_point('toulligqc==0.5', 'console_scripts', 'toulligqc')()
  File "/usr/local/lib/python3.5/dist-packages/toulligqc/toulligqc.py", line 212, in main
    check_conf(config_dictionary)
  File "/usr/local/lib/python3.5/dist-packages/toulligqc/toulligqc.py", line 137, in check_conf
    config_dictionary['result_directory'] = config_dictionary['result_directory'] + '/' + config_dictionary['run_name'] + '/'
TypeError: Can't convert 'NoneType' object to str implicitly
```

And the second is this one:

``` 
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/bio/miniconda3/lib/python3.6/site-packages/pandas-0.19.2-py3.6-linux-x86_64.egg/pandas/__init__.py", line 25, in <module>
    from pandas import hashtable, tslib, lib
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bio/miniconda3/bin/toulligqc", line 11, in <module>
    load_entry_point('toulligqc===-0.1a1-', 'console_scripts', 'toulligqc')()
  File "/home/bio/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/bio/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/bio/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/bio/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/bio/miniconda3/lib/python3.6/site-packages/toulligqc-_0.1a1_-py3.6.egg/toulligqc/toulligqc.py", line 36, in <module>
    from toulligqc import fastq_extractor
  File "/home/bio/miniconda3/lib/python3.6/site-packages/toulligqc-_0.1a1_-py3.6.egg/toulligqc/fastq_extractor.py", line 28, in <module>
    import pandas as pd
  File "/home/bio/miniconda3/lib/python3.6/site-packages/pandas-0.19.2-py3.6-linux-x86_64.egg/pandas/__init__.py", line 31, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: umpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```
Trying to solve it, I've updated all the libraries, updated python, I removed and reinstalled the libraries and those problems still occur.  
Do you know about what is happening? Is it something from the command line? or the python version? or is something from the libraries? 
Honestly, I don't know which is the problem? 
Could you help me please, 

Thanks in advance.
Luis Alfonso

**Comment by laffayb** [comment]
Hi,

Could-you send me your system configuration (OS, Python and Numpy version...) and your command line to see the origin of the issue ?

Bérengère

**Comment by OnlyHigh** [comment]
Error 1,
toulligqc -f ./ReadsFused/readstobasecall/ -a ./ReadsPosApolo23ago2017/albacore_rebasecall/ -q ./ReadsPosApolo23ago2017/allnanopolish.fastq -o Essay1

Numpy version: 1.12.1
Python version: 3.6.2
OS: Ubuntu 16.04.3 LTS

Error 2, 
Numpy 1.12.1 (conda) and 1.13.1(pip)
Python 3.6.1
OS Ubuntu 16.04.3 LTS
toulligqc -n Essay1 -f ./FAST5/reads_ex_tmp/ -a ./albacore_basecalltmps/sequencing_summary.txt -o ./Output_Essay1


Thank you, 
Luis Alfonso

**Comment by laffayb** [comment]
Hi, 
I recommend you to use Ubuntu 17.04, a virtualenv  or the easiest solution: our Docker image (genomicpariscentre/toulligqc:latest) that works well as we use it for all our MinION runs.
Try this command line : 
toulligqc -n Essay1 -f ./FAST5/reads_ex_tmp/ -a ./albacore_basecalltmps/sequencing_summary.txt -q ./ReadsPosApolo23ago2017/allnanopolish.fastq -o ./Output_Essay1

Best regards,
Bérengère

**Comment by OnlyHigh** [comment]
Hi, 
That worked, 

Thanks, 
Luis Alfonso.
