### ISSUE TITLE
unable to open fast5 files

### ISSUE THREAD

**Issue by RoelsJana** [GenomicParisCentre/toulligQC#7]
I'm running toulligqc on very recent fast5 files and get the following error:

```
ToulligQC version 1.1
* Initialize extractors
* Start Sequencing telemetry extractor
* End of Sequencing telemetry extractor (done in 00:00:00)
* Start Fast5 extractor
Traceback (most recent call last):
  File "/home/jroels/miniconda3/envs/toulligqc/bin/toulligqc", line 10, in <module>
    sys.exit(main())
  File "/home/jroels/miniconda3/envs/toulligqc/lib/python3.6/site-packages/toulligqc/toulligqc.py", line 354, in main
    extractor.extract(result_dict)
  File "/home/jroels/miniconda3/envs/toulligqc/lib/python3.6/site-packages/toulligqc/fast5_extractor.py", line 115, in extract
    result_dict['sequencing.telemetry.extractor.flowcell.id'] = self._get_fast5_items(h5py_file, 'flow_cell_id')
  File "/home/jroels/miniconda3/envs/toulligqc/lib/python3.6/site-packages/toulligqc/fast5_extractor.py", line 230, in _get_fast5_items
    tracking_id_items = list(h5py_file["/UniqueGlobalKey/tracking_id"].attrs.items())
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jroels/miniconda3/envs/toulligqc/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (component not found)'
```
I don't find the cause of the problem, anyone who can help?

**Comment by jourdren** [comment]
Hi,
ToulligQC does not actually support new multi-FAST5 format generated by newer versions of MinKNOW. We plan to support it soon.

However, you do not need to use anymore a FAST5 file with ToulligQC. I recommend you to provide instead a "sequencing_telemetry.js" when the --telemetry-source option. This file also contain all FAST5 metadata used by ToulligQC. When ToulligQC was created, "sequencing_telemetry.js" files were not generated by basecallers.

Best regards,

Laurent.

**Comment by RoelsJana** [comment]
I'll try that (maybe monday, maybe tuesday)
Thank you in advance!
Jana

**Comment by RoelsJana** [comment]
It worked thank you!
Jana
